# Generated by Django 3.2 on 2021-04-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
    ]
