# Generated by Django 3.2 on 2021-04-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_answers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.exam'),
        ),
    ]
