# Generated by Django 3.2.4 on 2021-06-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_first', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Todo',
        ),
    ]
