# Generated by Django 3.2.4 on 2021-06-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_first', '0002_rename_title_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='puplished',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
